### ISSUE TITLE
Wrong message about start date

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/ProcessPolls#2]
I have set a poll with start and end date, but the poll is inactive:
`This poll / election has not started yet. Participation is possible from 2022-02-20 to 2022-02-28.`

![image](https://user-images.githubusercontent.com/7663992/155385147-b536519e-f080-4550-b444-3a6bb573b214.png)

![image](https://user-images.githubusercontent.com/7663992/155384981-23801c2f-060c-4a55-b1dc-fb09eeb741e0.png)

The current system date on my computer/webserver is 23. February 2022. I voted yesterday.

**Comment by kixe** [comment]
Thanks for pointing on this. fixed
